name: window_utils
description: A flutter plugin for managing window decoration.
version: 1.1.0
authors:
  - Rhodes Davis Jr. <rody.davis.jr@gmail.com>
  - Rive <info@rive.app>
homepage: https://github.com/rive-app/window-utils

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.12.8 <2.0.0"

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: WindowUtils
      macos:
        pluginClass: WindowUtils
      windows:
        pluginClass: WindowUtilsPlugin

dependencies:
  flutter:
    sdk: flutter
